function [fitresult1, gof1, fitresult2, gof2] = createFit(X1, Y1, X2, Y2)
%CREATEFIT(NMI,MEAN_AHP_TIME)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: nmi
%      Y Output: Mean_AHP_time
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jan-2025 15:13:42


%% Fit 1

[xData1, yData1] = prepareCurveData( X1, Y1 );

% Set up fittype and options.
ft1 = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Lower = [0 -Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult1, gof1] = fit( xData1, yData1, ft1, opts );

%% Fit 2

[xData2, yData2] = prepareCurveData( X2, Y2 );

% Set up fittype and options.
ft2 = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Lower = [0 -Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult2, gof2] = fit( xData2, yData2, ft2 );

% Plot fit with data.

figure
hold on
yyaxis left
h1 = plot( fitresult1, xData1, yData1);
% Label axes
ylabel( 'UAV-AHP Time (Sec.)', 'Interpreter', 'none' );
ylim([0.4 1.4]);
grid on

yyaxis right
h2 = plot( fitresult2, xData2, yData2 );
legend(["Measured Data (UAV-AHP)", "Curve Fitting (UAV-AHP)","Measured Data (CS)", "Curve Fitting (CS)"],'Location', ...
    'NorthWest','FontSize',12,'Interpreter','none')

% Label axes
xlabel( 'Number of Iterations (Ni)', 'Interpreter', 'none' );
ylabel( 'CS Time (Sec.)', 'Interpreter', 'none' );
xticks(X1);
ylim([0 38]);
grid on
hold off


